# Example GitHub Actions workflow for Zephyr projects
# Copy this to .github/workflows/build.yml in your Zephyr project

name: Build Zephyr Application

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board: [qemu_x86, qemu_cortex_m3, native_posix]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Zephyr application
        run: |
          # Initialize and update Zephyr workspace
          source ~/.venv/bin/activate
          west init -l .
          west update

          # Build for target board
          west build -b ${{ matrix.board }} app

          # Optional: Upload build artifacts
          mkdir -p artifacts
          cp build/zephyr/zephyr.* artifacts/ 2>/dev/null || true
        # Use pre-built container image
        container:
          image: ghcr.io/tobiwan88/zephyr_docker:arm

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-${{ matrix.board }}
          path: artifacts/
          retention-days: 7

  test:
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.event.head_commit.message, '[test]') || github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests on native_posix
        run: |
          source ~/.venv/bin/activate
          west init -l .
          west update

          # Build and run tests
          west build -b native_posix tests
          ./build/zephyr/zephyr.exe
        container:
          image: ghcr.io/tobiwan88/zephyr_docker:arm
